WMO_MAPS = {
    "ru": {
        0: "Ясно",
        1: "Преимущественно ясно",
        2: "Переменная облачность",
        3: "Пасмурно",
        45: "Туман",
        48: "Оседающий туман (иней)",
        51: "Морось слабая",
        53: "Морось",
        55: "Морось сильная",
        56: "Ледяная морось слабая",
        57: "Ледяная морось сильная",
        61: "Дождь слабый",
        63: "Дождь",
        65: "Дождь сильный",
        66: "Ледяной дождь слабый",
        67: "Ледяной дождь сильный",
        71: "Снег слабый",
        73: "Снег",
        75: "Снег сильный",
        77: "Снежные зёрна",
        80: "Ливни слабые",
        81: "Ливни",
        82: "Ливни сильные",
        85: "Снежные ливни слабые",
        86: "Снежные ливни сильные",
        95: "Гроза",
        96: "Гроза с градом (слабая/умер.)",
        99: "Гроза с градом (сильная)",
    },
    "en": {
        0: "Clear sky",
        1: "Mainly clear",
        2: "Partly cloudy",
        3: "Overcast",
        45: "Fog",
        48: "Depositing rime fog",
        51: "Light drizzle",
        53: "Moderate drizzle",
        55: "Dense drizzle",
        56: "Light freezing drizzle",
        57: "Dense freezing drizzle",
        61: "Slight rain",
        63: "Moderate rain",
        65: "Heavy rain",
        66: "Light freezing rain",
        67: "Heavy freezing rain",
        71: "Slight snow",
        73: "Moderate snow",
        75: "Heavy snow",
        77: "Snow grains",
        80: "Slight rain showers",
        81: "Moderate rain showers",
        82: "Violent rain showers",
        85: "Slight snow showers",
        86: "Heavy snow showers",
        95: "Thunderstorm",
        96: "Thunderstorm with slight hail",
        99: "Thunderstorm with heavy hail",
    },
    "de": {
        0: "Klarer Himmel",
        1: "Hauptsächlich klar",
        2: "Teilweise bewölkt",
        3: "Bedeckt",
        45: "Nebel",
        48: "Reifnebel",
        51: "Leichter Nieselregen",
        53: "Mäßiger Nieselregen",
        55: "Dichter Nieselregen",
        56: "Leichter gefrierender Nieselregen",
        57: "Dichter gefrierender Nieselregen",
        61: "Leichter Regen",
        63: "Mäßiger Regen",
        65: "Starker Regen",
        66: "Leichter gefrierender Regen",
        67: "Starker gefrierender Regen",
        71: "Leichter Schnee",
        73: "Mäßiger Schnee",
        75: "Starker Schnee",
        77: "Schneekörner",
        80: "Leichte Regenschauer",
        81: "Mäßige Regenschauer",
        82: "Heftige Regenschauer",
        85: "Leichte Schneeschauer",
        86: "Starke Schneeschauer",
        95: "Gewitter",
        96: "Gewitter mit leichtem Hagel",
        99: "Gewitter mit schwerem Hagel",
    },
}

WMO_MAP_RU = WMO_MAPS["ru"]


def wmo_to_text(code: int | None, lang: str = "ru") -> str:
    if code is None:
        return "—"

    wmo_map = WMO_MAPS.get(lang, WMO_MAPS["ru"])
    if code in wmo_map:
        return wmo_map[code]

    fallback_messages = {
        "ru": f"Код погоды {code}",
        "en": f"Weather code {code}",
        "de": f"Wettercode {code}",
    }
    return fallback_messages.get(lang, f"Код погоды {code}")
