name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: The bot doesn't respond to /weather command...
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Send /start to the bot
        2. Send /weather Moscow
        3. Bot doesn't respond...
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Bot should return weather information for Moscow
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Bot returned an error message or didn't respond
    validations:
      required: true
      
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Which environment are you using?
      options:
        - Development
        - Production
        - Docker
        - Local setup
    validations:
      required: true
      
  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you running?
      placeholder: "3.11.5"
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Any relevant logs (please remove sensitive information)
      placeholder: |
        [ERROR] weatherbot.handlers.commands: Failed to process command...
      render: shell
      
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have removed any sensitive information from logs
          required: true