name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: As a user, I would like to...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your solution to the problem
      placeholder: Add a new command /forecast that shows...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any alternative solutions or workarounds you've considered
      placeholder: Could also be implemented as...
      
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New command
        - UI/UX improvement
        - Performance enhancement
        - Security improvement
        - Developer experience
        - Documentation
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for many users
        - Critical - Blocking current functionality
    validations:
      required: true
      
  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. User wants to see 7-day weather forecast
        2. User wants to compare weather in multiple cities
        
  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Please check all that apply
      options:
        - label: This feature affects internationalization (i18n)
        - label: This feature requires database changes
        - label: This feature affects the API/external services
        - label: This feature requires new permissions
        - label: I'm willing to help implement this feature
        
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature aligns with the project's goals
          required: true