name: ❓ Question
description: Ask a question about usage, configuration, or development
title: "[Question] "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!
        
  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What type of question is this?
      options:
        - Usage - How to use the bot
        - Configuration - Setup and environment
        - Development - Contributing to the project
        - Architecture - Understanding the codebase
        - Deployment - Running in production
        - Other
    validations:
      required: true
      
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I configure the bot for multiple languages?
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Additional context that might help answer your question
      placeholder: |
        I'm trying to deploy the bot to a server with Docker...
        I've read the documentation but...
        
  - type: textarea
    id: tried
    attributes:
      label: What Have You Tried?
      description: What solutions have you already attempted?
      placeholder: |
        1. Checked the README.md
        2. Looked at example configurations
        3. Searched existing issues
        
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have read the documentation (README.md, CONTRIBUTING.md)
          required: true