name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

permissions:
  contents: read

jobs:
  lint:
    name: Lint & Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run isort check
        run: isort --check-only --diff .
      - name: Run black check
        run: black --check .
      - name: Run flake8
        run: flake8 weatherbot

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run tests (with coverage)
        run: |
          python -m pytest --cov=weatherbot --cov-report=term-missing --cov-report=xml tests/

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run Bandit
        run: bandit -c .bandit -r weatherbot/

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [ test, security ]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: telegram-weather-bot-pub:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max